import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Container, Grid, Typography, Button } from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ background: "#FFF", height: "100vh" }} maxWidth={false}>
        <Box textAlign="center" padding={20}>
          <Typography variant="h3" color="black">
            Redirect Page
          </Typography>
        </Box>
        <Grid container>
          <Grid item xs={6} display="flex" justifyContent="center">
            <Link href="/weather-app">
              <Button
                sx={{
                  color: "#FFF",
                  width: 400,
                  height: 100,
                  borderRadius: 2,
                  fontSize: 22,
                  background: "rgba(255,0,0,1)",
                  "&:hover": {
                    background: "rgba(255,0,0,0.7)",
                  },
                }}
              >
                WEATHER APP
              </Button>
            </Link>
          </Grid>
          <Grid item xs={6} display="flex" justifyContent="center">
            <Link href="/mini-store">
              <Button
                sx={{
                  color: "#FFF",
                  width: 400,
                  height: 100,
                  borderRadius: 2,
                  fontSize: 22,
                  background: "rgba(255,0,0,1)",
                  "&:hover": {
                    background: "rgba(255,0,0,0.7)",
                  },
                }}
              >
                MINI STORE
              </Button>
            </Link>
          </Grid>
        </Grid>
      </Container>
    </>
  );
}
